import { colors, radius, shadow, spacing } from "./tokens";

export const cardStyles = {
  primary: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.line,
    ...shadow.card,
  },
  standard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radius.lg,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    ...shadow.card,
  },
  primaryTint: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(216, 163, 104, 0.34)",
    ...shadow.card,
  },
  secondary: {
    backgroundColor: colors.surfaceTint,
    borderRadius: radius.lg,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    ...shadow.card,
  },
  tertiary: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.lg,
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.lineSoft,
  },
  utility: {
    backgroundColor: colors.surfaceTint,
    borderRadius: radius.lg,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
  },
  imageFrame: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: 8,
    borderWidth: 1,
    borderColor: colors.line,
    ...shadow.card,
  },
  imageFrameInner: {
    backgroundColor: "rgba(5, 11, 20, 0.92)",
    borderRadius: radius.sm,
    overflow: "hidden" as const,
  },
};

export const buttonStyles = {
  primary: {
    backgroundColor: colors.primaryDeep,
    borderRadius: radius.pill,
    minHeight: 56,
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[4],
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 1,
    borderColor: "rgba(216, 163, 104, 0.34)",
    ...shadow.floating,
  },
  secondary: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.pill,
    minHeight: 52,
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[3],
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 1,
    borderColor: colors.line,
  },
  chip: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 1,
    borderColor: colors.line,
  },
};
