import { colors, radius, shadow, spacing } from "./tokens";

export const cardStyles = {
  primary: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing[6],
    borderWidth: 1,
    borderColor: colors.line,
    ...shadow.cardStrong,
  },
  standard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radius.lg,
    padding: spacing[5],
    borderWidth: 1,
    borderColor: colors.line,
    ...shadow.card,
  },
  primaryTint: {
    backgroundColor: colors.surfaceTint,
    borderRadius: radius.lg,
    padding: spacing[6],
    borderWidth: 1,
    borderColor: colors.primary,
    ...shadow.cardStrong,
  },
  secondary: {
    backgroundColor: colors.surfaceTint,
    borderRadius: radius.md,
    padding: spacing[5],
    borderWidth: 1,
    borderColor: colors.line,
    ...shadow.card,
  },
  tertiary: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.md,
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.lineSoft,
  },
  utility: {
    backgroundColor: colors.surfaceTint,
    borderRadius: radius.md,
    padding: spacing[5],
    borderWidth: 1,
    borderColor: colors.line,
  },
};

export const buttonStyles = {
  primary: {
    backgroundColor: colors.primaryDeep,
    borderRadius: radius.pill,
    minHeight: 56,
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[4],
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 1,
    borderColor: "rgba(94, 231, 255, 0.32)",
    ...shadow.floating,
  },
  secondary: {
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    minHeight: 52,
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[3],
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 1,
    borderColor: colors.line,
  },
  chip: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 1,
    borderColor: colors.line,
  },
};
