insert into public.vehicles (
  id,
  year,
  make,
  model,
  trim,
  body_style,
  vehicle_type,
  msrp,
  engine,
  horsepower,
  torque,
  transmission,
  drivetrain,
  mpg_or_range,
  colors
)
values
  (
    '2021-cadillac-ct4-premium-luxury',
    2021,
    'Cadillac',
    'CT4',
    'Premium Luxury',
    'Sedan',
    'car',
    41190,
    '2.0L Turbo I4',
    237,
    '258 lb-ft',
    '8-speed Automatic',
    'RWD',
    '23 city / 34 hwy',
    '["Summit White","Black Raven","Wave Metallic"]'::jsonb
  ),
  (
    '2020-honda-civic-ex',
    2020,
    'Honda',
    'Civic',
    'EX',
    'Sedan',
    'car',
    24550,
    '1.5L Turbo I4',
    174,
    '162 lb-ft',
    'CVT',
    'FWD',
    '32 city / 42 hwy',
    '["Modern Steel Metallic","Lunar Silver Metallic","Aegean Blue Metallic"]'::jsonb
  ),
  (
    '2019-ford-mustang-gt',
    2019,
    'Ford',
    'Mustang',
    'GT',
    'Coupe',
    'car',
    35995,
    '5.0L V8',
    460,
    '420 lb-ft',
    '6-speed Manual',
    'RWD',
    '15 city / 24 hwy',
    '["Race Red","Shadow Black","Velocity Blue"]'::jsonb
  ),
  (
    '2022-tesla-model-3-long-range',
    2022,
    'Tesla',
    'Model 3',
    'Long Range',
    'Sedan',
    'car',
    50990,
    'Dual Motor Electric',
    449,
    '389 lb-ft est.',
    'Single-speed',
    'AWD',
    '358 miles EPA est.',
    '["Pearl White Multi-Coat","Solid Black","Deep Blue Metallic"]'::jsonb
  ),
  (
    '2021-yamaha-yzf-r3-standard',
    2021,
    'Yamaha',
    'YZF-R3',
    'Standard',
    'Sport Bike',
    'motorcycle',
    5299,
    '321cc Parallel-Twin',
    42,
    '21.8 lb-ft',
    '6-speed Manual',
    'Chain',
    '56 mpg est.',
    '["Team Yamaha Blue","Matte Stealth Black"]'::jsonb
  ),
  (
    '2023-harley-davidson-street-glide-special',
    2023,
    'Harley-Davidson',
    'Street Glide',
    'Special',
    'Touring Motorcycle',
    'motorcycle',
    30399,
    'Milwaukee-Eight 114 V-Twin',
    95,
    '122 lb-ft',
    '6-speed Manual',
    'Belt',
    '43 mpg est.',
    '["Vivid Black","Redline Red","White Sand Pearl"]'::jsonb
  )
on conflict (id) do update set
  year = excluded.year,
  make = excluded.make,
  model = excluded.model,
  trim = excluded.trim,
  body_style = excluded.body_style,
  vehicle_type = excluded.vehicle_type,
  msrp = excluded.msrp,
  engine = excluded.engine,
  horsepower = excluded.horsepower,
  torque = excluded.torque,
  transmission = excluded.transmission,
  drivetrain = excluded.drivetrain,
  mpg_or_range = excluded.mpg_or_range,
  colors = excluded.colors;

insert into public.valuations (
  id,
  vehicle_id,
  zip,
  mileage,
  condition,
  trade_in,
  private_party,
  dealer_retail,
  currency,
  generated_at
)
values
  (
    'val-ct4',
    '2021-cadillac-ct4-premium-luxury',
    '60610',
    28000,
    'very_good',
    25600,
    27400,
    29300,
    'USD',
    now()
  ),
  (
    'val-civic',
    '2020-honda-civic-ex',
    '60610',
    36000,
    'good',
    17900,
    19250,
    20800,
    'USD',
    now()
  ),
  (
    'val-model3',
    '2022-tesla-model-3-long-range',
    '60610',
    18400,
    'excellent',
    33200,
    34950,
    36750,
    'USD',
    now()
  ),
  (
    'val-mustang',
    '2019-ford-mustang-gt',
    '60610',
    30118,
    'very_good',
    31600,
    33250,
    34995,
    'USD',
    now()
  ),
  (
    'val-street-glide',
    '2023-harley-davidson-street-glide-special',
    '60610',
    4188,
    'excellent',
    26950,
    28250,
    29495,
    'USD',
    now()
  )
on conflict (id) do update set
  vehicle_id = excluded.vehicle_id,
  zip = excluded.zip,
  mileage = excluded.mileage,
  condition = excluded.condition,
  trade_in = excluded.trade_in,
  private_party = excluded.private_party,
  dealer_retail = excluded.dealer_retail,
  currency = excluded.currency,
  generated_at = excluded.generated_at;

insert into public.listing_results (
  id,
  vehicle_id,
  title,
  price,
  mileage,
  dealer,
  distance_miles,
  location,
  image_url,
  listed_at
)
values
  (
    'listing-1',
    '2022-tesla-model-3-long-range',
    '2022 Tesla Model 3 Long Range',
    35990,
    21404,
    'Lakefront EV',
    7,
    'Chicago, IL',
    'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=900&q=80',
    now()
  ),
  (
    'listing-2',
    '2019-ford-mustang-gt',
    '2019 Ford Mustang GT Premium',
    33850,
    30118,
    'North Avenue Performance',
    13,
    'Elmhurst, IL',
    'https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&w=900&q=80',
    now()
  ),
  (
    'listing-3',
    '2023-harley-davidson-street-glide-special',
    '2023 Harley-Davidson Street Glide Special',
    28695,
    4188,
    'Windy City Harley',
    18,
    'Rosemont, IL',
    'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80',
    now()
  )
on conflict (id) do update set
  vehicle_id = excluded.vehicle_id,
  title = excluded.title,
  price = excluded.price,
  mileage = excluded.mileage,
  dealer = excluded.dealer,
  distance_miles = excluded.distance_miles,
  location = excluded.location,
  image_url = excluded.image_url,
  listed_at = excluded.listed_at;
